package gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import gui.imagemFrame;
import gui.imagemPanel;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import quantizacaoimagem.Imagem;
import quantizacaoimagem.QuantizacaoImagem;
import static quantizacaoimagem.QuantizacaoImagem.CAMINHONOVAIMAGEM;

/**
 *
 * @author FREE
 */
public class CarregarView extends javax.swing.JFrame {
    private boolean modoInvalido = false;
    private String decodedPath;
    private imagemPanel dPanelbuffer = null;
    private static JFileChooser fcBuffer = null;
    private File fileBuffer = null;
    /**
     * Creates new form CarregarView
     */
    public CarregarView(){
        initComponents();
        String path = CarregarView.class.getProtectionDomain().getCodeSource().getLocation().getPath();
        centralizarJanela(this);
        drawPanel.setLayout(new FlowLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCarregar = new javax.swing.JButton();
        btQuantizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAvisos = new javax.swing.JTextArea();
        btSalvar = new javax.swing.JButton();
        btSubtrair = new javax.swing.JButton();
        btConverter16to24 = new javax.swing.JButton();
        drawPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5), "CarregarCena"));

        btCarregar.setText("Carregar");
        btCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarActionPerformed(evt);
            }
        });

        btQuantizar.setText("Quantizar");
        btQuantizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuantizarActionPerformed(evt);
            }
        });

        taAvisos.setColumns(20);
        taAvisos.setRows(5);
        jScrollPane1.setViewportView(taAvisos);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btSubtrair.setText("Subtrair");
        btSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtrairActionPerformed(evt);
            }
        });

        btConverter16to24.setText("Converter 16-24");
        btConverter16to24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConverter16to24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btQuantizar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConverter16to24, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 265, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btCarregar)
                    .addComponent(btQuantizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSubtrair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConverter16to24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        drawPanel.setBackground(new java.awt.Color(153, 153, 153));
        drawPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("BMP","bmp","arquivo bmp");
        if (fcBuffer==null)
        {
            fcBuffer = new JFileChooser();
        }
        fcBuffer.setFileFilter(filter);
        
        int returnVal = fcBuffer.showOpenDialog(this);
        
        try{
            if (returnVal == JFileChooser.APPROVE_OPTION)
            {
                File file = fcBuffer.getSelectedFile();
                fileBuffer = file;
                if (dPanelbuffer==null){
                    imagemPanel imgPanel = new imagemPanel(file);
                    imgPanel.setVisible(true);
                    drawPanel.add(imgPanel);
                    drawPanel.repaint();
                    dPanelbuffer = imgPanel;
                    dPanelbuffer.repaint();
                    drawPanel.revalidate();
                }else{
                    dPanelbuffer.changeImage(file);
                    drawPanel.repaint();
                    dPanelbuffer.repaint();
                }
            }
            else
            {
                //this.setVisible(true);
            }
        }
        catch( Exception e)
        {
            //this.setVisible(true);
            taAvisos.setText("Erro e = " + e.getMessage());
        }
        System.out.println("end");
    }//GEN-LAST:event_btCarregarActionPerformed

    private void btQuantizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuantizarActionPerformed
        // TODO add your handling code here:
        if (!(dPanelbuffer==null)){
            drawPanel.updateUI();
            dPanelbuffer.quantizar();
            drawPanel.repaint();
            dPanelbuffer.repaint();
        }else{
            System.out.println("no image selected");
        }
    }//GEN-LAST:event_btQuantizarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (!(fileBuffer==null)){
            File outFile16 = new File(fileBuffer.getParent()+"\\test16.bmp");
            File outFile24 = new File(fileBuffer.getParent()+"\\test24.bmp");
            FileOutputStream escreverSaida16 = null;
            FileOutputStream escreverSaida24 = null;
            try {
                escreverSaida16 = new FileOutputStream(outFile16);
                escreverSaida24 = new FileOutputStream(outFile24);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CarregarView.class.getName()).log(Level.SEVERE, null, ex);
            }

            Imagem img = dPanelbuffer.getImagem();

            try {        
                //img.escreverNovaImagem24Bits(escreverSaida);
                img.escreverNovaImagem16Bits(escreverSaida16);
                img.escreverNovaImagem24Bits(escreverSaida24);
            } catch (IOException ex) {
                Logger.getLogger(CarregarView.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                escreverSaida16.close();
                escreverSaida24.close();
            } catch (IOException ex) {
                Logger.getLogger(CarregarView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtrairActionPerformed
        // TODO add your handling code here:
        if (!(dPanelbuffer==null)){
            FileNameExtensionFilter filter = new FileNameExtensionFilter("BMP","bmp","arquivo bmp");
            if (fcBuffer==null)
            {
                fcBuffer = new JFileChooser();
            }
            fcBuffer.setFileFilter(filter);

            int returnVal = fcBuffer.showOpenDialog(this);

            try{
                if (returnVal == JFileChooser.APPROVE_OPTION)
                {
                    File file = fcBuffer.getSelectedFile();
                    fileBuffer = file;
                    imagemPanel imgPanel = new imagemPanel(file);
                    
                    Imagem img1 = dPanelbuffer.getImagem();
                    int imagemWidth1 = QuantizacaoImagem.binarioParaDecimal(img1.getBiWidth());
                    int imagemHeight1 = QuantizacaoImagem.binarioParaDecimal(img1.getBiHeight());
                    
                    Imagem img2 = imgPanel.getImagem();
                    int imagemWidth2 = QuantizacaoImagem.binarioParaDecimal(img2.getBiWidth());
                    int imagemHeight2 = QuantizacaoImagem.binarioParaDecimal(img2.getBiHeight());
                    
                    if (imagemWidth1==imagemWidth2&&imagemHeight1==imagemHeight2){
                        System.out.println("subTraindo!");
                        drawPanel.updateUI();
                        dPanelbuffer.subtrair(img2);
                        drawPanel.repaint();
                        dPanelbuffer.repaint();
                    }else{
                        System.out.println("tamanhos incopativeis");
                    }
                }
                else
                {
                    //this.setVisible(true);
                }
            }
            catch( Exception e)
            {
                //this.setVisible(true);
                taAvisos.setText("Erro e = " + e.getMessage());
            }
        }
     
        System.out.println("end");
    }//GEN-LAST:event_btSubtrairActionPerformed

    private void btConverter16to24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConverter16to24ActionPerformed
        if (!(dPanelbuffer==null)){
            FileNameExtensionFilter filter = new FileNameExtensionFilter("BMP","bmp","arquivo bmp");
            if (fcBuffer==null)
            {
                fcBuffer = new JFileChooser();
            }
            fcBuffer.setFileFilter(filter);

            int returnVal = fcBuffer.showOpenDialog(this);

            try{
                if (returnVal == JFileChooser.APPROVE_OPTION)
                {
                    File file = fcBuffer.getSelectedFile();
                    fileBuffer = file;
                    imagemPanel imgPanel = new imagemPanel(file);
                    
                    Imagem img1 = dPanelbuffer.getImagem();
                    int imagemWidth1 = QuantizacaoImagem.binarioParaDecimal(img1.getBiWidth());
                    int imagemHeight1 = QuantizacaoImagem.binarioParaDecimal(img1.getBiHeight());
                    
                    
                    
                }
                else
                {
                    //this.setVisible(true);
                }
            }
            catch( Exception e)
            {
                //this.setVisible(true);
                taAvisos.setText("Erro e = " + e.getMessage());
            }
        }
     
        System.out.println("end");
    }//GEN-LAST:event_btConverter16to24ActionPerformed
    public static void centralizarJanela(JFrame janela)
    {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        janela.setLocation(dim.width/2-janela.getSize().width/2, dim.height/2-janela.getSize().height/2);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarregarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarregarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarregarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarregarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarregarView().setVisible(true);
            }
        });
    }
    
    private void aoFechar()
    {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCarregar;
    private javax.swing.JButton btConverter16to24;
    private javax.swing.JButton btQuantizar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSubtrair;
    private javax.swing.JPanel drawPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taAvisos;
    // End of variables declaration//GEN-END:variables

}

